NAME= ../libfSub.so
TYPE= SHARED
SRCS= Bitmap.cpp \
	Bubble.cpp \
	Calender.cpp \
	CustomListItem.cpp \
	FlickerFreeStringView.cpp \
	Postit.cpp \
	Save.cpp
LIBS= be \
	$(STDCPPLIBS)
RSRCS= 
DEFINES= 
LIBPATHS= 

SYSTEM_INCLUDE_PATHS = 
LOCAL_INCLUDE_PATHS = 
DRIVER_PATH = 

APP_VERSION = 
DEBUGGER = 
LINKER_FLAGS = 
CFLAGS= -fpermissive
SYMBOLS = 
WARNINGS = 

## Include the Makefile-Engine
DEVEL_DIRECTORY := \
	$(shell findpaths -r "makefile_engine" B_FIND_PATH_DEVELOP_DIRECTORY)
include $(DEVEL_DIRECTORY)/etc/makefile-engine
