NAME= ../libfSub.so
TYPE= SHARED
SRCS= Bitmap.cpp \
	Bubble.cpp \
	Calender.cpp \
	CustomListItem.cpp \
	FlickerFreeStringView.cpp \
	Postit.cpp \
	Save.cpp
LIBS= be \
	$(STDCPPLIBS)
RSRCS= 
DEFINES= 
LIBPATHS= 

SYSTEM_INCLUDE_PATHS = 
LOCAL_INCLUDE_PATHS = 
DRIVER_PATH = 

APP_VERSION = 
DEBUGGER = 
LINKER_FLAGS = 
CFLAGS= -fpermissive
SYMBOLS = 
WARNINGS = 

## include the makefile-engine
include $(BUILDHOME)/etc/makefile-engine

