NAME= ../../../Organizer
TYPE= APP
SRCS=aboutWindow.cpp \
	aboutView.cpp \
	calenderView.cpp \
	Constants.cpp \
	main.cpp \
	editApointmentView.cpp \
	editNoteView.cpp \
	editScriptView.cpp \
	editWindow.cpp \
	exportView.cpp \
	exportWindow.cpp \
	mWindow.cpp \
	menuView.cpp \
	navigateDateView.cpp \
	noteListView.cpp \
	preferencesWindow.cpp \
	preferencesView.cpp \
	Secret/glView.cpp \
	Secret/glWindow.cpp
RSRCS= Project.rsrc
LIBS= be \
	$(STDCPPLIBS) \
	game \
	GL \
	tracker \
	translation \
	fSub
DEFINES= 
LIBPATHS= ../lib

SYSTEM_INCLUDE_PATHS = 
LOCAL_INCLUDE_PATHS = 
DRIVER_PATH = 

APP_VERSION = 
DEBUGGER = 
LINKER_FLAGS = 
CFLAGS= -fpermissive
SYMBOLS = 
WARNINGS = 

## include the makefile-engine
include /system/develop/etc/makefile-engine

